package:
    name: cspy
    version: 2.0

source:
    path: {{ environ.get('CSPY_PATH', './.') }}

build:
    script: {{ PYTHON }} setup.py install

requirements:
    build:
        - conda-build
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cython
        - setuptools
        - numpy >=1.12, <2.0.0
        - pytest-runner
        - python

    host:
        - dask>=2.3.0
        - distributed>=2.3.0
        - jinja2>=2.10
        - msgpack-python==0.6.2
        - numpy>=1.16.4, <2.0.0
        - pandas>=0.25.0
        - paramiko>=2.6.0
        - pip>=19.1.1
        - psutil>=5.6.3
        - python=3.7.10
        - ipython
        - rtree>=0.8.3
        - scikit-learn>=0.21.2
        - scipy>=1.3.0
        - setuptools>=41.0.1
        - six=1.12.0
        - sphinx>=2.1.2
        - sqlite>=3.29.0
        - sympy>=1.4
        - wheel>=0.33.4
        - toml>=0.10.0
        - tqdm>=4.32.2
        - cython
        - gfortran_linux-64
        - gcc_linux-64
        - gxx_linux-64
        - spglib
        - networkx
        - mpi4py
        - attrs
        - rdkit

    run:
        - dask>=2.3.0
        - distributed>=2.3.0
        - jinja2>=2.10
        - msgpack-python==0.6.2
        - numpy>=1.16.4, <2.0.0
        - pandas>=0.25.0
        - paramiko>=2.6.0
        - pip>=19.1.1
        - psutil>=5.6.3
        - python=3.7.10
        - ipython
        - rtree>=0.8.3
        - scikit-learn>=0.21.2
        - scipy>=1.3.0
        - setuptools>=41.0.1
        - six=1.12.0
        - sphinx>=2.1.2
        - sqlite>=3.29.0
        - sympy>=1.4
        - wheel>=0.33.4
        - toml>=0.10.0
        - tqdm>=4.32.2
        - cython
        - gfortran_linux-64
        - gcc_linux-64
        - gxx_linux-64
        - spglib
        - networkx
        - mpi4py
        - attrs
        - rdkit
test:
    imports:
        - cspy
    requires:
        - python
        - pytest
        - pandas

about:
    home: https://bitbucket.org/gmdgroup/cspy-git.git